export const CANVAS_WIDTH = 480;
export const CANVAS_HEIGHT = 720;
export const PLAYER_MAX_SPEED = 200;
export const PLAYER_ACCELERATION = 800;
export const PLAYER_DAMPING = 0.85;
export const INITIAL_SCROLL_SPEED = 100;
export const MAX_SCROLL_SPEED = 300;
export const SCROLL_SPEED_INCREMENT = 5;
export const FISH_SCORE = 10;
export const STARFISH_SCORE = 25;
export const TREASURE_SCORE = 100;
export const PLAYER_MAX_HP = 4;
export const INVINCIBILITY_DURATION = 1.0;
export const SCREEN_SHAKE_DURATION = 0.3;
export const SCREEN_SHAKE_MAGNITUDE = 6;
export const SHINY_CHEST_SCORE = 200;
export const LASER_DURATION = 12;
export const LASER_DRAIN_RATE = 1 / 12; // gauge units per second while laser fires
export const LEVEL2_SCORE_THRESHOLD = 1000;
export const LEVEL3_SCORE_THRESHOLD = 2500;
export const SQUID_MAX_HP = 3; // ≈2.5× hits rounded up
export const SQUID_LASER_HIT_INTERVAL = 0.25; // seconds between laser damage ticks on squid
export const GAUGE_PER_EAT = 0.1;
export const SHIELD_DURATION = 10;
export const RED_TREASURE_SCORE = 150;
export const PEARL_ORBIT_RADIUS = 70;
export const PEARL_SPIN_SPEED = 2.0;
export const PEARL_HIT_RADIUS = 12;
export const PEARL_DRAW_RADIUS = 9;
export const EXPLOSION_PARTICLE_COUNT = 40;
export const SHOCKWAVE_INITIAL_RADIUS = 4;
export const SHOCKWAVE_MAX_RADIUS = 60;
export const SHOCKWAVE_DURATION = 0.4;
